/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactForm = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const NewsletterSubscription = IDL.Record({
  'email' : IDL.Text,
  'timestamp' : Time,
});
export const PartnerRegistration = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'businessType' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAllNewsletterSubscriptions' : IDL.Func(
      [],
      [IDL.Vec(NewsletterSubscription)],
      ['query'],
    ),
  'getAllPartnerRegistrations' : IDL.Func(
      [],
      [IDL.Vec(PartnerRegistration)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitPartnerRegistration' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactForm = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const NewsletterSubscription = IDL.Record({
    'email' : IDL.Text,
    'timestamp' : Time,
  });
  const PartnerRegistration = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'businessType' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAllNewsletterSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSubscription)],
        ['query'],
      ),
    'getAllPartnerRegistrations' : IDL.Func(
        [],
        [IDL.Vec(PartnerRegistration)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitPartnerRegistration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };